### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by Viveksati5143**

### CODE REVIEW

**Review by melvincwng — CHANGES_REQUESTED** [review]
@Viveksati5143, kindly add your entry at the bottom of the list.

There should only be **1 line of code change**.

Please do not change & rearrange the order of the other contributors.

PR still needs additional changes before it can be merged.

**Comment by Viveksati5143** [comment]
Done @melvincwng

**Review by melvincwng — APPROVED** [review]
LGTM!

**Comment by melvincwng** [comment]
Hey there,

Thanks for your PR & contribution :wave:!

Don't forget to join **follow me**, **join our organization**, & **follow our organization** to stay updated with the latest developments 💻

Thank you, and have a good day ahead 😊

**Pull request merged**
